<a href="https://colab.research.google.com/github/Yasir323/100-days-of-code/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

`yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`

In [2]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [3]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [4]:
kanto_yield_of_apples = w1 * kanto_temp + w2 * kanto_rainfall + w3 * kanto_humidity

In [5]:
kanto_yield_of_apples

56.8

In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [7]:
weights = [w1, w2, w3]

In [10]:
!python --version

Python 3.7.10


In [12]:
def dot_product(xs, ws):
  result = 0
  for x, w in zip(xs, ws):
    result += x * w
  return result

In [15]:
yield_of_apples = dot_product(kanto, weights)
yield_of_apples

56.8

In [16]:
kanto = np.array([73, 67, 43])
kanto

array([73, 67, 43])

In [17]:
weights = np.array([w1, w2, w3])
weights

array([0.3, 0.2, 0.5])

In [18]:
np.dot(kanto, weights)

56.8

In [20]:
(kanto * weights).sum()

56.8

In [21]:
# Lists
arr1 = [*range(1000000)]
arr2 = [*range(1000000, 2000000)]

In [22]:
# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [23]:
import sys

In [24]:
sys.getsizeof(arr1)

9000120

In [25]:
sys.getsizeof(arr1_np)

8000096

In [26]:
%%time
for a in arr1:
  a ** 2

CPU times: user 281 ms, sys: 0 ns, total: 281 ms
Wall time: 291 ms


In [27]:
%%time
for a in arr1_np:
  a ** 2

CPU times: user 374 ms, sys: 0 ns, total: 374 ms
Wall time: 381 ms


In [29]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
  result += x1 * x2
print(result)

833332333333500000
CPU times: user 194 ms, sys: 0 ns, total: 194 ms
Wall time: 195 ms


In [30]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2.69 ms, sys: 875 µs, total: 3.57 ms
Wall time: 2.74 ms


833332333333500000

In [32]:
%%time
arr1_np @ arr2_np

CPU times: user 2.55 ms, sys: 0 ns, total: 2.55 ms
Wall time: 2.61 ms


833332333333500000

* Size of Numpy array is smaller compared to lists.
* Normal operations are faster in lists.
* But computation is faster in Numpy arrays.

## Multi-dimensional Numpy arrays
<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png">

In [33]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [35]:
climate_data.shape

(5, 3)

In [36]:
climate_data.dtype

dtype('int64')

<img src="https://i.imgur.com/LJ2WKSI.png">

In [38]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [39]:
climate_data.ndim

2

In [40]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt'
)

('climate.txt', <http.client.HTTPMessage at 0x7fb34839b750>)

In [41]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [42]:
climate_data.shape

(10000, 3)

In [43]:
yields = climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [44]:
yields.shape

(10000,)

In [51]:
yields = yields.reshape(yields.shape[0], 1)

In [52]:
yields.shape

(10000, 1)

In [53]:
climate_results = np.concatenate((climate_data, yields), axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [54]:
np.savetxt(
    'climate_results.txt',
    climate_results,
    fmt='%.2f',
    delimiter=',',
    header='temperature,ranifall,humidity,yield_of_apples',
    comments=''
)

In [55]:
import os

In [57]:
os.listdir()

['.config', 'climate_results.txt', 'climate.txt', 'sample_data']