<a href="https://colab.research.google.com/github/Yasir323/100-days-of-code/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

`yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`

In [2]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [3]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [4]:
kanto_yield_of_apples = w1 * kanto_temp + w2 * kanto_rainfall + w3 * kanto_humidity

In [5]:
kanto_yield_of_apples

56.8

In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [7]:
weights = [w1, w2, w3]

In [8]:
!python --version

Python 3.7.10


In [9]:
def dot_product(xs, ws):
  result = 0
  for x, w in zip(xs, ws):
    result += x * w
  return result

In [10]:
yield_of_apples = dot_product(kanto, weights)
yield_of_apples

56.8

In [11]:
kanto = np.array([73, 67, 43])
kanto

array([73, 67, 43])

In [12]:
weights = np.array([w1, w2, w3])
weights

array([0.3, 0.2, 0.5])

In [13]:
np.dot(kanto, weights)

56.8

In [14]:
(kanto * weights).sum()

56.8

In [15]:
# Lists
arr1 = [*range(1000000)]
arr2 = [*range(1000000, 2000000)]

In [16]:
# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [17]:
import sys

In [18]:
sys.getsizeof(arr1)

9000120

In [19]:
sys.getsizeof(arr1_np)

8000096

In [20]:
%%time
for a in arr1:
  a ** 2

CPU times: user 296 ms, sys: 1.44 ms, total: 297 ms
Wall time: 303 ms


In [21]:
%%time
for a in arr1_np:
  a ** 2

CPU times: user 423 ms, sys: 5.4 ms, total: 428 ms
Wall time: 432 ms


In [22]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
  result += x1 * x2
print(result)

833332333333500000
CPU times: user 213 ms, sys: 529 µs, total: 214 ms
Wall time: 216 ms


In [23]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2.87 ms, sys: 989 µs, total: 3.86 ms
Wall time: 3 ms


833332333333500000

In [24]:
%%time
arr1_np @ arr2_np

CPU times: user 2.1 ms, sys: 10 µs, total: 2.11 ms
Wall time: 3.02 ms


833332333333500000

* Size of Numpy array is smaller compared to lists.
* Normal operations are faster in lists.
* But computation is faster in Numpy arrays.

## Multi-dimensional Numpy arrays
<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png">

In [25]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [26]:
climate_data.shape

(5, 3)

In [27]:
climate_data.dtype

dtype('int64')

<img src="https://i.imgur.com/LJ2WKSI.png">

In [28]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [29]:
climate_data.ndim

2

In [30]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt'
)

('climate.txt', <http.client.HTTPMessage at 0x7f7238a335d0>)

In [31]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [32]:
climate_data.shape

(10000, 3)

In [33]:
yields = climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [34]:
yields.shape

(10000,)

In [35]:
yields = yields.reshape(yields.shape[0], 1)

In [36]:
yields.shape

(10000, 1)

In [37]:
climate_results = np.concatenate((climate_data, yields), axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [38]:
np.savetxt(
    'climate_results.txt',
    climate_results,
    fmt='%.2f',
    delimiter=',',
    header='temperature,ranifall,humidity,yield_of_apples',
    comments=''
)

In [39]:
import os

In [40]:
os.listdir()

['.config', 'climate_results.txt', 'climate.txt', 'sample_data']

In [41]:
a = np.array([1, 2, 3, 4.5])
np.sum(a)

10.5

In [43]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 90.0171313 ])

In [44]:
# np.round() To round off digits

In [45]:
a.shape

(4,)

In [52]:
a = a.reshape((4, 1))

In [53]:
a.shape

(4, 1)

In [55]:
b = np.ones((4, 1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [59]:
a = np.array([1, 2, 3, 4.5])
b = np.ones((4))

In [60]:
c = np.stack([a, b])
c

array([[1. , 2. , 3. , 4.5],
       [1. , 1. , 1. , 1. ]])

In [66]:
x, y, z, w = np.split(a, 4)

In [67]:
x

array([1.])

In [68]:
c.shape

(2, 4)

In [70]:
np.transpose(c).shape

(4, 2)

In [71]:
np.mean(c)

1.8125

In [72]:
np.median(c)

1.0

In [74]:
np.std(c)

1.2231491119238078

In [75]:
np.min(c)

1.0

In [76]:
np.max(c)

4.5

In [83]:
arr = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
])
arr1 = np.array([
        [13, 14,15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
])

In [84]:
# Adding a scalar
arr + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [85]:
# Element wise addition
arr + arr1

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [86]:
arr / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [87]:
# Element wise multiplication
arr * arr1

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [88]:
arr % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0]])

In [89]:
arr1

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [90]:
arr1.shape

(3, 4)

In [92]:
a.shape

(4,)

In [93]:
arr1 + a

array([[14. , 16. , 18. , 20.5],
       [18. , 20. , 22. , 24.5],
       [22. , 24. , 26. , 28.5]])

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [95]:
np.arange(3).reshape((3, 1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

***Broadcasting only works if one of the arrays can be replicated to match the other array's shape.***

In [100]:
# Following cannot be broadcasted together
# np.arange(6).reshape((3, 2)) + np.arange(5)

In [103]:
arr1 == arr

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [104]:
arr1 != arr

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [107]:
(arr1 == arr).sum()

0

In [110]:
arr1[1:, 1]

array([18, 22])

In [111]:
arr1[1]

array([17, 18, 19, 20])

In [112]:
arr1[1][3]

20

In [113]:
arr1[1, 3]

20

In [116]:
# arr1[1, 2, 3] # Error

In [117]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [118]:
np.ones([2, 3, 4, 5])  # 4-D array

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [119]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [125]:
np.full([2, 3], 33)

array([[33, 33, 33],
       [33, 33, 33]])

In [128]:
np.array(np.arange(10, 100, 5)).reshape(3, 3, 2)

array([[[10, 15],
        [20, 25],
        [30, 35]],

       [[40, 45],
        [50, 55],
        [60, 65]],

       [[70, 75],
        [80, 85],
        [90, 95]]])